import "./globals.css";


export const metadata = {
  title: "File Analyser",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col items-center justify-center min-h-screen bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
